import sqlite3
connect = sqlite3.connect('database.db')
print()
print("TABLES")
print(connect.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall())
print()
print("TWEETS")
print(connect.execute('''SELECT * FROM TWEETS LIMIT 5''').fetchall())
print()
print("EMOTIONS")
print(connect.execute('''SELECT * FROM EMOTIONS LIMIT 5''').fetchall())
print()
print("USERS")
print(connect.execute('''SELECT * FROM USERS LIMIT 5''').fetchall())
print()
print("RESPONSES")
print(connect.execute('''SELECT * FROM RESPONSES LIMIT 5''').fetchall())
print()
